{% set name = "Bamsurgeon" %}
{% set version = "1.0.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/Tim15-tech/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 64c36f560b10c2931eae2a0aaf8fea8d477e05826c173a1b1efb9249f414ee44

build:
  run_exports:    
    - {{ pin_subpackage('bamsurgeon', max_pin="x") }}
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv ."
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - samtools >=1.2
    - bwa >=0.7.12
    - exonerate >=2.2
    - velvet >=1.2
    - pysam
    - picard

test:
  commands:
    - addsv -h | grep ALIGNERTHREADS

about:
  home: https://github.com/adamewing/bamsurgeon
  license: MIT-license
  license_file: LICENSE.txt
  summary: Tools for adding genomic variants to BAM/SAM/CRAM files. Can be used to test variant callers.
