{% set name = "NEAT" %}
{% set version = "4.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/ncsa/NEAT/archive/4.0.tar.gz
  sha256: 89abf23f202e4e93fc333a2b6f2a7c7b63ef3db691f8372b659d8627df3616c3
  

build:
  run_exports:    
    - {{ pin_subpackage('neat', max_pin="x") }}
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv ."
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - biopython =1.79
    - pkginfo
    - matplotlib-base
    - numpy
    - seaborn
    - pyyaml
    - scipy
    - pytest
    - bedtools
    - htslib
    - pysam
    - frozendict
    - poetry >=1.3.*

test:
  commands:
    - neat --help

about:
  home: https://github.com/ncsa/NEAT/
  license: BSD-3-clause
  license_file: LICENSE
  summary: Toolset for generating synthethic FASTQ, VCF and BAM files.
